# Generated by Django 3.1 on 2020-08-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IotDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=20)),
                ('mac_adrress', models.BigIntegerField()),
                ('factory_id', models.CharField(max_length=50)),
                ('approval_status', models.CharField(max_length=3)),
                ('installed_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('gateway_id', models.IntegerField()),
                ('public_space_id', models.IntegerField()),
                ('room_id', models.IntegerField()),
                ('supported_device_id', models.IntegerField()),
            ],
        ),
    ]
